import {
  GetServerSideProps,
  GetServerSidePropsContext,
  type NextPage,
} from "next";
import Head from "next/head";
import Link from "next/link";
import { redirect } from "next/navigation";
import { useEffect, useState } from "react";
import Spotify from "spotify-web-api-js";
import { fetchSpotify } from "~/util/api/spotify";
import readExcel, { Row } from "read-excel-file";
import { BsSpotify } from "react-icons/bs";
import { useRouter } from "next/router";

const spotifyApi = new Spotify();

const Home: NextPage<{ code?: string }, {}> = ({ code }) => {
  const router = useRouter();

  useEffect(() => {
    if (!code) return;

    fetchSpotify(code).then(({ access_token }) => {
      spotifyApi.setAccessToken(access_token);
      router.push("/create-playlist");
    });
  }, [code]);

  return (
    <>
      <Head>
        <title>ITU ROCK</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export async function getServerSideProps({
  query,
  req,
}: GetServerSidePropsContext) {
  console.log(query);
  // console.log(req);

  // const queryParamString = new URLSearchParams(query).toString();
  return {
    props: {
      code: query.code ?? null,
    },
  };
}

export default Home;
