import { type NextPage } from "next";
import Head from "next/head";
import { BsSpotify } from "react-icons/bs";
import { env } from "~/env.mjs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ITU ROCK</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-[90vh] w-full items-center justify-center">
        <a
          className="flex items-center justify-center bg-[#1ED760] px-4 py-2"
          href={`https://accounts.spotify.com/authorize?response_type=code&client_id=95b8b69022e944268212e5d0e373bd89&scope=playlist-modify-public&redirect_uri=${env.NEXT_PUBLIC_SPOTIFY_REDIRECT}`}
        >
          <BsSpotify size={24} color="white" />
          <p className="ml-2 text-white">Giriş Yap</p>
        </a>
      </main>
    </>
  );
};

export default Home;
